# Generated by Django 5.0 on 2025-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_cart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
