# Generated by Django 5.0 on 2025-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_added_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_cart',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
