# Generated by Django 5.0 on 2025-10-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_added_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_cart',
            new_name='is_added_to_cart',
        ),
    ]
