# Generated by Django 5.0 on 2025-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_added_cart_product_is_added_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
