# Generated by Django 5.0 on 2025-10-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
