# Generated by Django 5.0 on 2025-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_address_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default-profile-image.png', null=True, upload_to='profile_images/'),
        ),
    ]
