# Generated by Django 5.0 on 2025-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='momo_reference',
            new_name='paystack_reference',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
