# Generated by Django 5.0 on 2025-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_momo_reference_order_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Delivery', 'On Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
